### ISSUE TITLE
pyrosm.OSM pygeos exception

### ISSUE THREAD

**Issue by r-leyshon** [r-leyshon/pyrosm-experiments#10]
About 40% of the boundaries extracted from `cropped_northern_line.osm.pbf` (source, planetOSM) result in pygeos exceptions. Some reading around online resulted in the following unsuccessful attempts at resolving:

- [x] try fix_geom() in the same fashion as access_to_services_OTP. i.e. Try `shapely.make_valid()` and if this doesn't work, use a buffer with a value of zero.
- [x]  Check if the workflow needs to change in cases where the returned boundary geometry is polygon vs multipolygon. This does not seem to be the cause.
- [x] Check if the problematic boundaries are empty or not Polygonal or LinearRing. No examples were found other than LinearRing.

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "<stdin>", line 23, in filter_buildings
  File "/opt/anaconda3/envs/pyrosm/lib/python3.9/site-packages/pyrosm/pyrosm.py", line 265, in get_buildings
    gdf = get_building_data(
  File "/opt/anaconda3/envs/pyrosm/lib/python3.9/site-packages/pyrosm/buildings.py", line 47, in get_building_data
    gdf = prepare_geodataframe(
  File "pyrosm/frames.pyx", line 134, in pyrosm.frames.prepare_geodataframe
  File "pyrosm/frames.pyx", line 185, in pyrosm.frames.prepare_geodataframe
  File "/opt/anaconda3/envs/pyrosm/lib/python3.9/site-packages/geopandas/tools/sjoin.py", line 124, in sjoin
    indices = _geom_predicate_query(left_df, right_df, predicate)
  File "/opt/anaconda3/envs/pyrosm/lib/python3.9/site-packages/geopandas/tools/sjoin.py", line 220, in _geom_predicate_query
    l_idx, r_idx = sindex.query_bulk(input_geoms, predicate=predicate, sort=False)
  File "/opt/anaconda3/envs/pyrosm/lib/python3.9/site-packages/geopandas/sindex.py", line 756, in query_bulk
    res = self._tree.query_bulk(geometry, predicate)
  File "/opt/anaconda3/envs/pyrosm/lib/python3.9/site-packages/pygeos/strtree.py", line 228, in query_bulk
    return self._tree.query_bulk(geometry, predicate)
pygeos.GEOSException: IllegalArgumentException: Argument must be Polygonal or LinearRing

```

**Comment by r-leyshon** [comment]
Next step: Test this issue against pyrosm data ingests for the same area.
